name: Check Solutions
on:
  pull_request:
    branches: [ main ]

jobs:
  check-solutions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt

    - name: Lint code
      run: |
        ruff check ./solutions ./homeworks

    - name: Check code format
      run: |
        ruff format --check ./solutions ./homeworks

    - name: Test code 
      run: |
        pytest -v --cov=./solutions ./tests/
      
    - name: Test code hw
      run: |
        pytest -v --cov=./homeworks ./tests_hw/
